# @package __global__

data:
  _target_: src.data.text_motion.TextMotionDataset

  name: ${dataset}

  split: ???
  min_seconds: 2.0
  max_seconds: 10.0
  preload: true
  tiny: false
  # dropping data
  drop_motion_perc: 0.10
  drop_cond: 0.10
  drop_trans: 0.5

diffusion:
  _target_: src.model.gaussian.GaussianDiffusion
  
  denoiser:
    _target_: src.model.mdm_smpl.TransformerDenoiser
    nfeats: ${data.motion_loader.nfeats}
    tx_dim: ${data.text_encoder.nfeats}  # Fixed: use correct field reference
    latent_dim: 512
    ff_size: 2048
    num_layers: 8
    num_heads: 8
    dropout: 0.1
    nb_registers: 2
    activation: gelu
    keyframe_conditioned: True  # Enable keyframe conditioning

  schedule:
    _target_: src.model.schedule.cosine.CosineBetaSchedule
    s: 0.008

  motion_normalizer:
    _target_: src.normalizer.Normalizer
    base_dir: datasets/stats/motion_stats
    eps: 1e-12

  text_normalizer:
    _target_: src.normalizer.Normalizer
    base_dir: datasets/stats/text_stats
    eps: 1e-12

  timesteps: 100
  prediction: x
  lr: 1e-4
  
  # Keyframe conditioning parameters
  keyframe_conditioned: True
  keyframe_selection_scheme: "random_frames"  # Options: random_frames, benchmark_sparse, benchmark_clip, pelvis_only, uncond, gmd_keyframes
  keyframe_mask_prob: 0.1  # Probability of dropping keyframes during training for robustness
  zero_keyframe_loss: False  # If True, zero out loss on keyframe regions (train only on non-keyframes)
  n_keyframes: 5  # Number of keyframes to sample for certain selection schemes 