# SRM-enhanced MDM configuration for motion diffusion
# Enables frame-level time sampling and loss weighting

diffusion:
  _target_: src.model.srm_gaussian.SRMGaussianDiffusion
  
  # Standard diffusion parameters
  schedule:
    _target_: src.model.schedule.cosine.CosineSchedule
    s: 8e-3
  timesteps: 1000
  lr: 1e-4
  prediction: "x"
  
  # Denoiser configuration
  denoiser:
    _target_: src.model.mdm_smpl.MotionDiffusion
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    num_layers: 8
    keyframe_conditioned: ${diffusion.keyframe_conditioned}
    
  # Data normalization  
  motion_normalizer:
    _target_: src.normalizer.Normalizer
    base_dir: ${run_dir}/motion_stats
    disable: false
    
  text_normalizer:
    _target_: src.normalizer.Normalizer
    base_dir: ${run_dir}/text_stats
    disable: false
    
  # Keyframe conditioning parameters
  keyframe_conditioned: true
  keyframe_selection_scheme: "random_frames"  # Options: "random_frames", "first_last", "uniform_spacing"
  keyframe_mask_prob: 0.1  # Probability to drop out keyframes during training
  zero_keyframe_loss: false  # Whether to zero out loss at keyframe positions
  n_keyframes: 10  # Number of keyframes to select
  keyframe_loss_weight: 2.0  # Loss weight for keyframes (if not zeroing)
  
  # SRM-specific parameters
  time_sampler_type: "mean_beta"  # Options: "mean_beta", "independent"
  time_sampler_sharpness: 1.0  # Controls concentration around mean time (higher = more concentrated)
  max_frames: 81  # Maximum number of frames in your dataset
  motion_features: 205  # Number of motion features per frame
  enable_frame_level_conditioning: true  # Whether to pass frame times to denoiser 